FROM neo4j:4.1.1

#ENV APOC_VERSION 4.1.01
#ENV APOC_URI https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/${APOC_VERSION}/apoc-${APOC_VERSION}-all.jar
#ENV ALGO_VERSION 3.4.4.0
#ENV ALGO_URI https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/${ALGO_VERSION}/graph-algorithms-algo-${ALGO_VERSION}.jar

#RUN cd /var/lib/neo4j/plugins && wget $APOC_URI

#RUN cd /var/lib/neo4j/plugins && wget $ALGO_URI

